# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'specify_XANES_files.ui'
#
# Created: Fri Aug 01 10:17:23 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1087, 889)
        self.sample_inputBox = QtGui.QGroupBox(Dialog)
        self.sample_inputBox.setGeometry(QtCore.QRect(10, 40, 481, 91))
        self.sample_inputBox.setObjectName(_fromUtf8("sample_inputBox"))
        self.samTxrm = QtGui.QRadioButton(self.sample_inputBox)
        self.samTxrm.setGeometry(QtCore.QRect(10, 30, 51, 17))
        self.samTxrm.setChecked(True)
        self.samTxrm.setObjectName(_fromUtf8("samTxrm"))
        self.samXrm = QtGui.QRadioButton(self.sample_inputBox)
        self.samXrm.setGeometry(QtCore.QRect(60, 30, 41, 17))
        self.samXrm.setObjectName(_fromUtf8("samXrm"))
        self.button_load_XANES = QtGui.QPushButton(self.sample_inputBox)
        self.button_load_XANES.setGeometry(QtCore.QRect(10, 60, 91, 23))
        self.button_load_XANES.setAutoDefault(False)
        self.button_load_XANES.setObjectName(_fromUtf8("button_load_XANES"))
        self.text_XANES_filename = QtGui.QLabel(self.sample_inputBox)
        self.text_XANES_filename.setGeometry(QtCore.QRect(110, 20, 361, 61))
        self.text_XANES_filename.setObjectName(_fromUtf8("text_XANES_filename"))
        self.bkg_inputBox = QtGui.QGroupBox(Dialog)
        self.bkg_inputBox.setGeometry(QtCore.QRect(10, 140, 481, 91))
        self.bkg_inputBox.setObjectName(_fromUtf8("bkg_inputBox"))
        self.bkgTxrm = QtGui.QRadioButton(self.bkg_inputBox)
        self.bkgTxrm.setGeometry(QtCore.QRect(10, 30, 51, 17))
        self.bkgTxrm.setChecked(True)
        self.bkgTxrm.setObjectName(_fromUtf8("bkgTxrm"))
        self.bkgXrm = QtGui.QRadioButton(self.bkg_inputBox)
        self.bkgXrm.setGeometry(QtCore.QRect(60, 30, 41, 17))
        self.bkgXrm.setObjectName(_fromUtf8("bkgXrm"))
        self.button_load_BKG = QtGui.QPushButton(self.bkg_inputBox)
        self.button_load_BKG.setEnabled(False)
        self.button_load_BKG.setGeometry(QtCore.QRect(10, 60, 91, 23))
        self.button_load_BKG.setAutoDefault(False)
        self.button_load_BKG.setObjectName(_fromUtf8("button_load_BKG"))
        self.text_BKG_filename = QtGui.QLabel(self.bkg_inputBox)
        self.text_BKG_filename.setGeometry(QtCore.QRect(110, 20, 361, 71))
        self.text_BKG_filename.setObjectName(_fromUtf8("text_BKG_filename"))
        self.alignment_checkBox = QtGui.QCheckBox(Dialog)
        self.alignment_checkBox.setEnabled(False)
        self.alignment_checkBox.setGeometry(QtCore.QRect(20, 240, 151, 17))
        self.alignment_checkBox.setObjectName(_fromUtf8("alignment_checkBox"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.reference_inputBox = QtGui.QGroupBox(Dialog)
        self.reference_inputBox.setGeometry(QtCore.QRect(10, 270, 481, 141))
        self.reference_inputBox.setObjectName(_fromUtf8("reference_inputBox"))
        self.label_2 = QtGui.QLabel(self.reference_inputBox)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 51, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.reference_inputBox)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.reference_inputBox)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 101, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.load_ref1 = QtGui.QPushButton(self.reference_inputBox)
        self.load_ref1.setGeometry(QtCore.QRect(120, 20, 101, 23))
        self.load_ref1.setAutoDefault(False)
        self.load_ref1.setObjectName(_fromUtf8("load_ref1"))
        self.load_ref2 = QtGui.QPushButton(self.reference_inputBox)
        self.load_ref2.setGeometry(QtCore.QRect(120, 60, 101, 23))
        self.load_ref2.setAutoDefault(False)
        self.load_ref2.setObjectName(_fromUtf8("load_ref2"))
        self.load_ref3 = QtGui.QPushButton(self.reference_inputBox)
        self.load_ref3.setGeometry(QtCore.QRect(120, 100, 101, 23))
        self.load_ref3.setAutoDefault(False)
        self.load_ref3.setObjectName(_fromUtf8("load_ref3"))
        self.ref1name = QtGui.QLabel(self.reference_inputBox)
        self.ref1name.setGeometry(QtCore.QRect(230, 20, 241, 21))
        self.ref1name.setObjectName(_fromUtf8("ref1name"))
        self.ref2name = QtGui.QLabel(self.reference_inputBox)
        self.ref2name.setGeometry(QtCore.QRect(230, 60, 241, 21))
        self.ref2name.setObjectName(_fromUtf8("ref2name"))
        self.ref3name = QtGui.QLabel(self.reference_inputBox)
        self.ref3name.setGeometry(QtCore.QRect(230, 100, 241, 21))
        self.ref3name.setObjectName(_fromUtf8("ref3name"))
        self.back_normal = QtGui.QPushButton(Dialog)
        self.back_normal.setEnabled(False)
        self.back_normal.setGeometry(QtCore.QRect(20, 420, 121, 31))
        self.back_normal.setAutoDefault(False)
        self.back_normal.setObjectName(_fromUtf8("back_normal"))
        self.status_bkgnorm = QtGui.QLabel(Dialog)
        self.status_bkgnorm.setGeometry(QtCore.QRect(150, 430, 91, 16))
        self.status_bkgnorm.setObjectName(_fromUtf8("status_bkgnorm"))
        self.orgView = QtGui.QGraphicsView(Dialog)
        self.orgView.setGeometry(QtCore.QRect(20, 460, 381, 381))
        self.orgView.setObjectName(_fromUtf8("orgView"))
        self.scaleBox = QtGui.QGroupBox(Dialog)
        self.scaleBox.setGeometry(QtCore.QRect(410, 460, 81, 381))
        self.scaleBox.setObjectName(_fromUtf8("scaleBox"))
        self.text_maxscale = QtGui.QLabel(self.scaleBox)
        self.text_maxscale.setGeometry(QtCore.QRect(10, 10, 61, 20))
        self.text_maxscale.setObjectName(_fromUtf8("text_maxscale"))
        self.label_7 = QtGui.QLabel(self.scaleBox)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 41, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.slider_img_maxscale = QtGui.QScrollBar(self.scaleBox)
        self.slider_img_maxscale.setEnabled(False)
        self.slider_img_maxscale.setGeometry(QtCore.QRect(30, 50, 21, 121))
        self.slider_img_maxscale.setSliderPosition(99)
        self.slider_img_maxscale.setOrientation(QtCore.Qt.Vertical)
        self.slider_img_maxscale.setInvertedAppearance(True)
        self.slider_img_maxscale.setInvertedControls(True)
        self.slider_img_maxscale.setObjectName(_fromUtf8("slider_img_maxscale"))
        self.label_8 = QtGui.QLabel(self.scaleBox)
        self.label_8.setGeometry(QtCore.QRect(30, 170, 21, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.text_minscale = QtGui.QLabel(self.scaleBox)
        self.text_minscale.setGeometry(QtCore.QRect(10, 190, 61, 20))
        self.text_minscale.setObjectName(_fromUtf8("text_minscale"))
        self.slider_img_minscale = QtGui.QScrollBar(self.scaleBox)
        self.slider_img_minscale.setEnabled(False)
        self.slider_img_minscale.setGeometry(QtCore.QRect(30, 230, 21, 121))
        self.slider_img_minscale.setOrientation(QtCore.Qt.Vertical)
        self.slider_img_minscale.setInvertedAppearance(True)
        self.slider_img_minscale.setInvertedControls(True)
        self.slider_img_minscale.setObjectName(_fromUtf8("slider_img_minscale"))
        self.label_10 = QtGui.QLabel(self.scaleBox)
        self.label_10.setGeometry(QtCore.QRect(30, 210, 31, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.scaleBox)
        self.label_11.setGeometry(QtCore.QRect(30, 360, 21, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.slider_img = QtGui.QScrollBar(Dialog)
        self.slider_img.setEnabled(False)
        self.slider_img.setGeometry(QtCore.QRect(20, 840, 381, 21))
        self.slider_img.setSliderPosition(99)
        self.slider_img.setOrientation(QtCore.Qt.Horizontal)
        self.slider_img.setObjectName(_fromUtf8("slider_img"))
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(80, 860, 81, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.current_img = QtGui.QLineEdit(Dialog)
        self.current_img.setEnabled(False)
        self.current_img.setGeometry(QtCore.QRect(170, 860, 51, 20))
        self.current_img.setObjectName(_fromUtf8("current_img"))
        self.total_img = QtGui.QLabel(Dialog)
        self.total_img.setGeometry(QtCore.QRect(230, 860, 111, 21))
        self.total_img.setObjectName(_fromUtf8("total_img"))
        self.processBox = QtGui.QGroupBox(Dialog)
        self.processBox.setGeometry(QtCore.QRect(510, 10, 561, 871))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.processBox.setFont(font)
        self.processBox.setObjectName(_fromUtf8("processBox"))
        self.select_point = QtGui.QPushButton(self.processBox)
        self.select_point.setEnabled(False)
        self.select_point.setGeometry(QtCore.QRect(20, 30, 151, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.select_point.setFont(font)
        self.select_point.setObjectName(_fromUtf8("select_point"))
        self.label_5 = QtGui.QLabel(self.processBox)
        self.label_5.setGeometry(QtCore.QRect(40, 60, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.processBox)
        self.label_6.setGeometry(QtCore.QRect(100, 60, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.x_cord = QtGui.QLineEdit(self.processBox)
        self.x_cord.setEnabled(False)
        self.x_cord.setGeometry(QtCore.QRect(50, 60, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.x_cord.setFont(font)
        self.x_cord.setObjectName(_fromUtf8("x_cord"))
        self.y_cord = QtGui.QLineEdit(self.processBox)
        self.y_cord.setEnabled(False)
        self.y_cord.setGeometry(QtCore.QRect(110, 60, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.y_cord.setFont(font)
        self.y_cord.setObjectName(_fromUtf8("y_cord"))
        self.label_9 = QtGui.QLabel(self.processBox)
        self.label_9.setGeometry(QtCore.QRect(40, 80, 46, 13))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.bin = QtGui.QLineEdit(self.processBox)
        self.bin.setEnabled(False)
        self.bin.setGeometry(QtCore.QRect(90, 80, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.bin.setFont(font)
        self.bin.setObjectName(_fromUtf8("bin"))
        self.label_13 = QtGui.QLabel(self.processBox)
        self.label_13.setGeometry(QtCore.QRect(210, 30, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.select_method = QtGui.QComboBox(self.processBox)
        self.select_method.setEnabled(False)
        self.select_method.setGeometry(QtCore.QRect(180, 60, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.select_method.setFont(font)
        self.select_method.setObjectName(_fromUtf8("select_method"))
        self.set_raw_bkg = QtGui.QPushButton(self.processBox)
        self.set_raw_bkg.setEnabled(False)
        self.set_raw_bkg.setGeometry(QtCore.QRect(180, 90, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.set_raw_bkg.setFont(font)
        self.set_raw_bkg.setObjectName(_fromUtf8("set_raw_bkg"))
        self.fit_base_line = QtGui.QPushButton(self.processBox)
        self.fit_base_line.setEnabled(False)
        self.fit_base_line.setGeometry(QtCore.QRect(180, 120, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fit_base_line.setFont(font)
        self.fit_base_line.setObjectName(_fromUtf8("fit_base_line"))
        self.base_line_zero = QtGui.QPushButton(self.processBox)
        self.base_line_zero.setEnabled(False)
        self.base_line_zero.setGeometry(QtCore.QRect(180, 150, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.base_line_zero.setFont(font)
        self.base_line_zero.setObjectName(_fromUtf8("base_line_zero"))
        self.check_select_zero = QtGui.QCheckBox(self.processBox)
        self.check_select_zero.setEnabled(False)
        self.check_select_zero.setGeometry(QtCore.QRect(270, 150, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.check_select_zero.setFont(font)
        self.check_select_zero.setObjectName(_fromUtf8("check_select_zero"))
        self.label_14 = QtGui.QLabel(self.processBox)
        self.label_14.setGeometry(QtCore.QRect(190, 190, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.edit_edge_jump = QtGui.QLineEdit(self.processBox)
        self.edit_edge_jump.setEnabled(False)
        self.edit_edge_jump.setGeometry(QtCore.QRect(260, 190, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.edit_edge_jump.setFont(font)
        self.edit_edge_jump.setObjectName(_fromUtf8("edit_edge_jump"))
        self.norm_spec = QtGui.QPushButton(self.processBox)
        self.norm_spec.setGeometry(QtCore.QRect(180, 220, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.norm_spec.setFont(font)
        self.norm_spec.setObjectName(_fromUtf8("norm_spec"))
        self.XANESnormStatus = QtGui.QLabel(self.processBox)
        self.XANESnormStatus.setGeometry(QtCore.QRect(280, 230, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.XANESnormStatus.setFont(font)
        self.XANESnormStatus.setObjectName(_fromUtf8("XANESnormStatus"))
        self.save_spectrum = QtGui.QPushButton(self.processBox)
        self.save_spectrum.setGeometry(QtCore.QRect(180, 262, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.save_spectrum.setFont(font)
        self.save_spectrum.setObjectName(_fromUtf8("save_spectrum"))
        self.default_scaling = QtGui.QCheckBox(self.processBox)
        self.default_scaling.setEnabled(False)
        self.default_scaling.setGeometry(QtCore.QRect(330, 30, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.default_scaling.setFont(font)
        self.default_scaling.setObjectName(_fromUtf8("default_scaling"))
        self.label_15 = QtGui.QLabel(self.processBox)
        self.label_15.setGeometry(QtCore.QRect(330, 60, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.processBox)
        self.label_16.setGeometry(QtCore.QRect(330, 100, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.processBox)
        self.label_17.setGeometry(QtCore.QRect(320, 140, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.pre_start = QtGui.QScrollBar(self.processBox)
        self.pre_start.setEnabled(False)
        self.pre_start.setGeometry(QtCore.QRect(350, 60, 81, 16))
        self.pre_start.setOrientation(QtCore.Qt.Horizontal)
        self.pre_start.setObjectName(_fromUtf8("pre_start"))
        self.pre_end = QtGui.QScrollBar(self.processBox)
        self.pre_end.setEnabled(False)
        self.pre_end.setGeometry(QtCore.QRect(430, 60, 81, 16))
        self.pre_end.setOrientation(QtCore.Qt.Horizontal)
        self.pre_end.setObjectName(_fromUtf8("pre_end"))
        self.post_start = QtGui.QScrollBar(self.processBox)
        self.post_start.setEnabled(False)
        self.post_start.setGeometry(QtCore.QRect(350, 100, 81, 16))
        self.post_start.setOrientation(QtCore.Qt.Horizontal)
        self.post_start.setObjectName(_fromUtf8("post_start"))
        self.post_end = QtGui.QScrollBar(self.processBox)
        self.post_end.setEnabled(False)
        self.post_end.setGeometry(QtCore.QRect(430, 100, 81, 16))
        self.post_end.setOrientation(QtCore.Qt.Horizontal)
        self.post_end.setObjectName(_fromUtf8("post_end"))
        self.edge_start = QtGui.QScrollBar(self.processBox)
        self.edge_start.setEnabled(False)
        self.edge_start.setGeometry(QtCore.QRect(350, 140, 81, 16))
        self.edge_start.setOrientation(QtCore.Qt.Horizontal)
        self.edge_start.setObjectName(_fromUtf8("edge_start"))
        self.edge_end = QtGui.QScrollBar(self.processBox)
        self.edge_end.setEnabled(False)
        self.edge_end.setGeometry(QtCore.QRect(430, 140, 81, 16))
        self.edge_end.setOrientation(QtCore.Qt.Horizontal)
        self.edge_end.setObjectName(_fromUtf8("edge_end"))
        self.label_18 = QtGui.QLabel(self.processBox)
        self.label_18.setGeometry(QtCore.QRect(420, 80, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.processBox)
        self.label_19.setGeometry(QtCore.QRect(420, 120, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.processBox)
        self.label_20.setGeometry(QtCore.QRect(420, 160, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.text_pre_start = QtGui.QLabel(self.processBox)
        self.text_pre_start.setGeometry(QtCore.QRect(360, 80, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.text_pre_start.setFont(font)
        self.text_pre_start.setObjectName(_fromUtf8("text_pre_start"))
        self.text_pre_end = QtGui.QLabel(self.processBox)
        self.text_pre_end.setGeometry(QtCore.QRect(450, 80, 46, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.text_pre_end.setFont(font)
        self.text_pre_end.setObjectName(_fromUtf8("text_pre_end"))
        self.text_post_start = QtGui.QLabel(self.processBox)
        self.text_post_start.setGeometry(QtCore.QRect(360, 120, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.text_post_start.setFont(font)
        self.text_post_start.setObjectName(_fromUtf8("text_post_start"))
        self.text_post_end = QtGui.QLabel(self.processBox)
        self.text_post_end.setGeometry(QtCore.QRect(450, 120, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.text_post_end.setFont(font)
        self.text_post_end.setObjectName(_fromUtf8("text_post_end"))
        self.text_edge_start = QtGui.QLabel(self.processBox)
        self.text_edge_start.setGeometry(QtCore.QRect(360, 160, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.text_edge_start.setFont(font)
        self.text_edge_start.setObjectName(_fromUtf8("text_edge_start"))
        self.text_edge_end = QtGui.QLabel(self.processBox)
        self.text_edge_end.setGeometry(QtCore.QRect(450, 160, 46, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.text_edge_end.setFont(font)
        self.text_edge_end.setObjectName(_fromUtf8("text_edge_end"))
        self.pre_plot = QtGui.QPushButton(self.processBox)
        self.pre_plot.setEnabled(False)
        self.pre_plot.setGeometry(QtCore.QRect(510, 60, 31, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pre_plot.setFont(font)
        self.pre_plot.setObjectName(_fromUtf8("pre_plot"))
        self.post_plot = QtGui.QPushButton(self.processBox)
        self.post_plot.setEnabled(False)
        self.post_plot.setGeometry(QtCore.QRect(510, 100, 31, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.post_plot.setFont(font)
        self.post_plot.setObjectName(_fromUtf8("post_plot"))
        self.edge_plot = QtGui.QPushButton(self.processBox)
        self.edge_plot.setEnabled(False)
        self.edge_plot.setGeometry(QtCore.QRect(510, 140, 31, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.edge_plot.setFont(font)
        self.edge_plot.setObjectName(_fromUtf8("edge_plot"))
        self.label_21 = QtGui.QLabel(self.processBox)
        self.label_21.setGeometry(QtCore.QRect(380, 190, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.smooth_pts = QtGui.QLineEdit(self.processBox)
        self.smooth_pts.setEnabled(False)
        self.smooth_pts.setGeometry(QtCore.QRect(470, 190, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.smooth_pts.setFont(font)
        self.smooth_pts.setObjectName(_fromUtf8("smooth_pts"))
        self.save_spectrum_fig = QtGui.QPushButton(self.processBox)
        self.save_spectrum_fig.setGeometry(QtCore.QRect(370, 220, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.save_spectrum_fig.setFont(font)
        self.save_spectrum_fig.setObjectName(_fromUtf8("save_spectrum_fig"))
        self.athena = QtGui.QPushButton(self.processBox)
        self.athena.setEnabled(True)
        self.athena.setGeometry(QtCore.QRect(370, 262, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.athena.setFont(font)
        self.athena.setObjectName(_fromUtf8("athena"))
        self.update_spectrum = QtGui.QPushButton(self.processBox)
        self.update_spectrum.setEnabled(False)
        self.update_spectrum.setGeometry(QtCore.QRect(20, 100, 151, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.update_spectrum.setFont(font)
        self.update_spectrum.setObjectName(_fromUtf8("update_spectrum"))
        self.plotView = QtGui.QGraphicsView(self.processBox)
        self.plotView.setGeometry(QtCore.QRect(20, 300, 521, 211))
        self.plotView.setObjectName(_fromUtf8("plotView"))
        self.label_22 = QtGui.QLabel(self.processBox)
        self.label_22.setGeometry(QtCore.QRect(310, 193, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.fittingView = QtGui.QGraphicsView(self.processBox)
        self.fittingView.setGeometry(QtCore.QRect(210, 530, 331, 331))
        self.fittingView.setObjectName(_fromUtf8("fittingView"))
        self.label_23 = QtGui.QLabel(self.processBox)
        self.label_23.setGeometry(QtCore.QRect(20, 530, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.fit_start = QtGui.QScrollBar(self.processBox)
        self.fit_start.setEnabled(False)
        self.fit_start.setGeometry(QtCore.QRect(20, 550, 91, 16))
        self.fit_start.setOrientation(QtCore.Qt.Horizontal)
        self.fit_start.setObjectName(_fromUtf8("fit_start"))
        self.fit_end = QtGui.QScrollBar(self.processBox)
        self.fit_end.setEnabled(False)
        self.fit_end.setGeometry(QtCore.QRect(110, 550, 91, 16))
        self.fit_end.setOrientation(QtCore.Qt.Horizontal)
        self.fit_end.setObjectName(_fromUtf8("fit_end"))
        self.text_fit_start = QtGui.QLabel(self.processBox)
        self.text_fit_start.setGeometry(QtCore.QRect(40, 570, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.text_fit_start.setFont(font)
        self.text_fit_start.setObjectName(_fromUtf8("text_fit_start"))
        self.text_fit_end = QtGui.QLabel(self.processBox)
        self.text_fit_end.setGeometry(QtCore.QRect(130, 570, 46, 13))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.text_fit_end.setFont(font)
        self.text_fit_end.setObjectName(_fromUtf8("text_fit_end"))
        self.label_24 = QtGui.QLabel(self.processBox)
        self.label_24.setGeometry(QtCore.QRect(100, 570, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.processBox)
        self.label_25.setGeometry(QtCore.QRect(20, 710, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.resolution = QtGui.QLineEdit(self.processBox)
        self.resolution.setEnabled(False)
        self.resolution.setGeometry(QtCore.QRect(100, 710, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.resolution.setFont(font)
        self.resolution.setText(_fromUtf8(""))
        self.resolution.setObjectName(_fromUtf8("resolution"))
        self.label_26 = QtGui.QLabel(self.processBox)
        self.label_26.setGeometry(QtCore.QRect(160, 710, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.processBox)
        self.label_27.setGeometry(QtCore.QRect(20, 740, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.Rmax = QtGui.QLineEdit(self.processBox)
        self.Rmax.setEnabled(False)
        self.Rmax.setGeometry(QtCore.QRect(100, 740, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Rmax.setFont(font)
        self.Rmax.setObjectName(_fromUtf8("Rmax"))
        self.update_image = QtGui.QPushButton(self.processBox)
        self.update_image.setEnabled(False)
        self.update_image.setGeometry(QtCore.QRect(20, 760, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.update_image.setFont(font)
        self.update_image.setObjectName(_fromUtf8("update_image"))
        self.bin_object = QtGui.QCheckBox(self.processBox)
        self.bin_object.setEnabled(False)
        self.bin_object.setGeometry(QtCore.QRect(20, 590, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.bin_object.setFont(font)
        self.bin_object.setObjectName(_fromUtf8("bin_object"))
        self.smooth_object = QtGui.QCheckBox(self.processBox)
        self.smooth_object.setEnabled(False)
        self.smooth_object.setGeometry(QtCore.QRect(20, 620, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.smooth_object.setFont(font)
        self.smooth_object.setObjectName(_fromUtf8("smooth_object"))
        self.fitting = QtGui.QPushButton(self.processBox)
        self.fitting.setEnabled(False)
        self.fitting.setGeometry(QtCore.QRect(110, 650, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fitting.setFont(font)
        self.fitting.setObjectName(_fromUtf8("fitting"))
        self.status_expXANES = QtGui.QLabel(self.processBox)
        self.status_expXANES.setGeometry(QtCore.QRect(20, 670, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.status_expXANES.setFont(font)
        self.status_expXANES.setObjectName(_fromUtf8("status_expXANES"))
        self.save_fitted = QtGui.QPushButton(self.processBox)
        self.save_fitted.setEnabled(False)
        self.save_fitted.setGeometry(QtCore.QRect(20, 790, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.save_fitted.setFont(font)
        self.save_fitted.setObjectName(_fromUtf8("save_fitted"))
        self.restart = QtGui.QPushButton(self.processBox)
        self.restart.setGeometry(QtCore.QRect(20, 830, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.restart.setFont(font)
        self.restart.setObjectName(_fromUtf8("restart"))
        self.fitting_method = QtGui.QComboBox(self.processBox)
        self.fitting_method.setGeometry(QtCore.QRect(20, 650, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.fitting_method.setFont(font)
        self.fitting_method.setObjectName(_fromUtf8("fitting_method"))
        self.listWidget = QtGui.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(530, 140, 151, 161))
        self.listWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.sample_inputBox.setTitle(_translate("Dialog", "Sample File", None))
        self.samTxrm.setText(_translate("Dialog", "txrm", None))
        self.samXrm.setText(_translate("Dialog", "xrm", None))
        self.button_load_XANES.setText(_translate("Dialog", "Browse Data", None))
        self.text_XANES_filename.setText(_translate("Dialog", "                                 XANES Sample directory & filename", None))
        self.bkg_inputBox.setTitle(_translate("Dialog", "Background File", None))
        self.bkgTxrm.setText(_translate("Dialog", "txrm", None))
        self.bkgXrm.setText(_translate("Dialog", "xrm", None))
        self.button_load_BKG.setText(_translate("Dialog", "Background", None))
        self.text_BKG_filename.setText(_translate("Dialog", "                              XANES Background directory & filename", None))
        self.alignment_checkBox.setText(_translate("Dialog", "apply pre-alignment in txrm", None))
        self.label.setText(_translate("Dialog", "Input Data", None))
        self.reference_inputBox.setTitle(_translate("Dialog", "Load Reference", None))
        self.label_2.setText(_translate("Dialog", "Ref1 - Red", None))
        self.label_3.setText(_translate("Dialog", "Ref2 - Green", None))
        self.label_4.setText(_translate("Dialog", "Ref3 - Blue(optional)", None))
        self.load_ref1.setText(_translate("Dialog", "Load Reference 1", None))
        self.load_ref2.setText(_translate("Dialog", "Load Reference 2", None))
        self.load_ref3.setText(_translate("Dialog", "Load Reference 3", None))
        self.ref1name.setText(_translate("Dialog", "                      no reference loaded", None))
        self.ref2name.setText(_translate("Dialog", "                      no reference loaded", None))
        self.ref3name.setText(_translate("Dialog", "                      no reference loaded", None))
        self.back_normal.setText(_translate("Dialog", "Load and Show Image", None))
        self.status_bkgnorm.setText(_translate("Dialog", "Status: none", None))
        self.scaleBox.setTitle(_translate("Dialog", "Scale", None))
        self.text_maxscale.setText(_translate("Dialog", "Max         %", None))
        self.label_7.setText(_translate("Dialog", "  100%", None))
        self.label_8.setText(_translate("Dialog", "0%", None))
        self.text_minscale.setText(_translate("Dialog", "Min          %", None))
        self.label_10.setText(_translate("Dialog", "100%", None))
        self.label_11.setText(_translate("Dialog", "0%", None))
        self.label_12.setText(_translate("Dialog", "Image Number:", None))
        self.total_img.setText(_translate("Dialog", "/ Total Image Number", None))
        self.processBox.setTitle(_translate("Dialog", "Process", None))
        self.select_point.setText(_translate("Dialog", "Select Point", None))
        self.label_5.setText(_translate("Dialog", "X:", None))
        self.label_6.setText(_translate("Dialog", "Y:", None))
        self.x_cord.setText(_translate("Dialog", "1", None))
        self.y_cord.setText(_translate("Dialog", "1", None))
        self.label_9.setText(_translate("Dialog", "Binning:", None))
        self.bin.setText(_translate("Dialog", "1", None))
        self.label_13.setText(_translate("Dialog", "Select Method :", None))
        self.set_raw_bkg.setText(_translate("Dialog", "Set as Raw Bkg", None))
        self.fit_base_line.setText(_translate("Dialog", "Fit Base Line", None))
        self.base_line_zero.setText(_translate("Dialog", "Base Line = 0", None))
        self.check_select_zero.setText(_translate("Dialog", "OK", None))
        self.label_14.setText(_translate("Dialog", "Edge Jump :", None))
        self.edit_edge_jump.setText(_translate("Dialog", "0", None))
        self.norm_spec.setText(_translate("Dialog", "Start Normalize", None))
        self.XANESnormStatus.setText(_translate("Dialog", "Status: none", None))
        self.save_spectrum.setText(_translate("Dialog", "Export Spectrum", None))
        self.default_scaling.setText(_translate("Dialog", "use default scaling (first/last 5 points)", None))
        self.label_15.setText(_translate("Dialog", "Pre", None))
        self.label_16.setText(_translate("Dialog", "Post", None))
        self.label_17.setText(_translate("Dialog", "Edge", None))
        self.label_18.setText(_translate("Dialog", "to", None))
        self.label_19.setText(_translate("Dialog", "to", None))
        self.label_20.setText(_translate("Dialog", "to", None))
        self.text_pre_start.setText(_translate("Dialog", "PreEstart", None))
        self.text_pre_end.setText(_translate("Dialog", "PreEend", None))
        self.text_post_start.setText(_translate("Dialog", "PostEstart", None))
        self.text_post_end.setText(_translate("Dialog", "PostEend", None))
        self.text_edge_start.setText(_translate("Dialog", "EdgeStart", None))
        self.text_edge_end.setText(_translate("Dialog", "EdgeEnd", None))
        self.pre_plot.setText(_translate("Dialog", "plot", None))
        self.post_plot.setText(_translate("Dialog", "plot", None))
        self.edge_plot.setText(_translate("Dialog", "plot", None))
        self.label_21.setText(_translate("Dialog", "Spectra Smooth :", None))
        self.smooth_pts.setText(_translate("Dialog", "1", None))
        self.save_spectrum_fig.setText(_translate("Dialog", "Save Spectrum Figure", None))
        self.athena.setText(_translate("Dialog", "Export to Athena", None))
        self.update_spectrum.setText(_translate("Dialog", "Plot Spectrum (selected)", None))
        self.label_22.setText(_translate("Dialog", "[0,255]", None))
        self.label_23.setText(_translate("Dialog", "Fitting Range:", None))
        self.text_fit_start.setText(_translate("Dialog", "Start Num", None))
        self.text_fit_end.setText(_translate("Dialog", "End Num", None))
        self.label_24.setText(_translate("Dialog", "to", None))
        self.label_25.setText(_translate("Dialog", "Resolution:", None))
        self.label_26.setText(_translate("Dialog", "%", None))
        self.label_27.setText(_translate("Dialog", "R-value Max:", None))
        self.update_image.setText(_translate("Dialog", "update image", None))
        self.bin_object.setText(_translate("Dialog", "apply binning to fitting", None))
        self.smooth_object.setText(_translate("Dialog", "apply smoothing to fitting", None))
        self.fitting.setText(_translate("Dialog", "Start Fit", None))
        self.status_expXANES.setText(_translate("Dialog", "status: none", None))
        self.save_fitted.setText(_translate("Dialog", "Save fitting result", None))
        self.restart.setText(_translate("Dialog", "Restart", None))

