# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Demo1.ui'
#
# Created: Tue Jul 08 15:59:10 2014
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(979, 554)
        self.ModifyElement = QtGui.QPushButton(Dialog)
        self.ModifyElement.setGeometry(QtCore.QRect(300, 300, 101, 23))
        self.ModifyElement.setObjectName(_fromUtf8("ModifyElement"))
        self.TopLeftX = QtGui.QLineEdit(Dialog)
        self.TopLeftX.setGeometry(QtCore.QRect(70, 280, 41, 20))
        self.TopLeftX.setObjectName(_fromUtf8("TopLeftX"))
        self.TopLeftY = QtGui.QLineEdit(Dialog)
        self.TopLeftY.setGeometry(QtCore.QRect(160, 280, 41, 20))
        self.TopLeftY.setObjectName(_fromUtf8("TopLeftY"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(53, 250, 171, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 320, 171, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(50, 30, 201, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(50, 50, 21, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(130, 50, 21, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(210, 50, 21, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.MotorPositionX = QtGui.QLineEdit(Dialog)
        self.MotorPositionX.setEnabled(False)
        self.MotorPositionX.setGeometry(QtCore.QRect(70, 50, 41, 20))
        self.MotorPositionX.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.MotorPositionX.setObjectName(_fromUtf8("MotorPositionX"))
        self.MotorPositionY = QtGui.QLineEdit(Dialog)
        self.MotorPositionY.setEnabled(False)
        self.MotorPositionY.setGeometry(QtCore.QRect(150, 50, 41, 21))
        self.MotorPositionY.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.MotorPositionY.setObjectName(_fromUtf8("MotorPositionY"))
        self.MotorPositionZ = QtGui.QLineEdit(Dialog)
        self.MotorPositionZ.setEnabled(False)
        self.MotorPositionZ.setGeometry(QtCore.QRect(230, 50, 41, 21))
        self.MotorPositionZ.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.MotorPositionZ.setObjectName(_fromUtf8("MotorPositionZ"))
        self.toMotorPositionY = QtGui.QLineEdit(Dialog)
        self.toMotorPositionY.setGeometry(QtCore.QRect(150, 80, 41, 21))
        self.toMotorPositionY.setObjectName(_fromUtf8("toMotorPositionY"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(50, 80, 21, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.toMotorPositionZ = QtGui.QLineEdit(Dialog)
        self.toMotorPositionZ.setGeometry(QtCore.QRect(230, 80, 41, 21))
        self.toMotorPositionZ.setObjectName(_fromUtf8("toMotorPositionZ"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(210, 80, 21, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(130, 80, 21, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.toMotorPositionX = QtGui.QLineEdit(Dialog)
        self.toMotorPositionX.setGeometry(QtCore.QRect(70, 80, 41, 20))
        self.toMotorPositionX.setObjectName(_fromUtf8("toMotorPositionX"))
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(50, 280, 21, 21))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(140, 280, 21, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(140, 340, 21, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(50, 340, 21, 21))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.ScanAreaWidth = QtGui.QLineEdit(Dialog)
        self.ScanAreaWidth.setGeometry(QtCore.QRect(70, 340, 41, 20))
        self.ScanAreaWidth.setObjectName(_fromUtf8("ScanAreaWidth"))
        self.ScanAreaHeight = QtGui.QLineEdit(Dialog)
        self.ScanAreaHeight.setGeometry(QtCore.QRect(160, 340, 41, 20))
        self.ScanAreaHeight.setObjectName(_fromUtf8("ScanAreaHeight"))
        self.shiftMotorPositionX = QtGui.QLineEdit(Dialog)
        self.shiftMotorPositionX.setGeometry(QtCore.QRect(70, 140, 41, 20))
        self.shiftMotorPositionX.setObjectName(_fromUtf8("shiftMotorPositionX"))
        self.shiftMotorPositionY = QtGui.QLineEdit(Dialog)
        self.shiftMotorPositionY.setGeometry(QtCore.QRect(150, 140, 41, 20))
        self.shiftMotorPositionY.setObjectName(_fromUtf8("shiftMotorPositionY"))
        self.shiftMotorPositionZ = QtGui.QLineEdit(Dialog)
        self.shiftMotorPositionZ.setGeometry(QtCore.QRect(230, 140, 41, 20))
        self.shiftMotorPositionZ.setObjectName(_fromUtf8("shiftMotorPositionZ"))
        self.changeMotorPositionX = QtGui.QPushButton(Dialog)
        self.changeMotorPositionX.setGeometry(QtCore.QRect(70, 110, 41, 23))
        self.changeMotorPositionX.setObjectName(_fromUtf8("changeMotorPositionX"))
        self.changeMotorPositionY = QtGui.QPushButton(Dialog)
        self.changeMotorPositionY.setGeometry(QtCore.QRect(150, 110, 41, 23))
        self.changeMotorPositionY.setObjectName(_fromUtf8("changeMotorPositionY"))
        self.changeMotorPositionZ = QtGui.QPushButton(Dialog)
        self.changeMotorPositionZ.setGeometry(QtCore.QRect(230, 110, 41, 23))
        self.changeMotorPositionZ.setObjectName(_fromUtf8("changeMotorPositionZ"))
        self.minusMotorPositionX = QtGui.QPushButton(Dialog)
        self.minusMotorPositionX.setGeometry(QtCore.QRect(50, 160, 41, 23))
        self.minusMotorPositionX.setObjectName(_fromUtf8("minusMotorPositionX"))
        self.plusMotorPositionX = QtGui.QPushButton(Dialog)
        self.plusMotorPositionX.setGeometry(QtCore.QRect(90, 160, 41, 23))
        self.plusMotorPositionX.setObjectName(_fromUtf8("plusMotorPositionX"))
        self.plusMotorPositionY = QtGui.QPushButton(Dialog)
        self.plusMotorPositionY.setGeometry(QtCore.QRect(170, 160, 41, 23))
        self.plusMotorPositionY.setObjectName(_fromUtf8("plusMotorPositionY"))
        self.minusMotorPositionY = QtGui.QPushButton(Dialog)
        self.minusMotorPositionY.setGeometry(QtCore.QRect(130, 160, 41, 23))
        self.minusMotorPositionY.setObjectName(_fromUtf8("minusMotorPositionY"))
        self.plusMotorPositionZ = QtGui.QPushButton(Dialog)
        self.plusMotorPositionZ.setGeometry(QtCore.QRect(250, 160, 41, 23))
        self.plusMotorPositionZ.setObjectName(_fromUtf8("plusMotorPositionZ"))
        self.minusMotorPositionZ = QtGui.QPushButton(Dialog)
        self.minusMotorPositionZ.setGeometry(QtCore.QRect(210, 160, 41, 23))
        self.minusMotorPositionZ.setObjectName(_fromUtf8("minusMotorPositionZ"))
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(50, 380, 171, 21))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(50, 410, 21, 21))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.ScanStepSizeX = QtGui.QLineEdit(Dialog)
        self.ScanStepSizeX.setGeometry(QtCore.QRect(70, 410, 41, 20))
        self.ScanStepSizeX.setObjectName(_fromUtf8("ScanStepSizeX"))
        self.ScanStepSizeY = QtGui.QLineEdit(Dialog)
        self.ScanStepSizeY.setGeometry(QtCore.QRect(160, 410, 41, 20))
        self.ScanStepSizeY.setObjectName(_fromUtf8("ScanStepSizeY"))
        self.label_19 = QtGui.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(140, 410, 21, 21))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.DwellTime = QtGui.QLineEdit(Dialog)
        self.DwellTime.setGeometry(QtCore.QRect(130, 440, 41, 20))
        self.DwellTime.setObjectName(_fromUtf8("DwellTime"))
        self.label_20 = QtGui.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(50, 440, 71, 21))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(180, 440, 31, 21))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(720, 300, 71, 21))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.TimeLeft = QtGui.QLineEdit(Dialog)
        self.TimeLeft.setEnabled(False)
        self.TimeLeft.setGeometry(QtCore.QRect(790, 300, 111, 20))
        self.TimeLeft.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.TimeLeft.setObjectName(_fromUtf8("TimeLeft"))
        self.ExecuteScan = QtGui.QPushButton(Dialog)
        self.ExecuteScan.setGeometry(QtCore.QRect(70, 470, 101, 23))
        self.ExecuteScan.setObjectName(_fromUtf8("ExecuteScan"))
        self.label_23 = QtGui.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(360, 30, 201, 21))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(700, 30, 201, 21))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.MoveToStartPoint = QtGui.QPushButton(Dialog)
        self.MoveToStartPoint.setGeometry(QtCore.QRect(50, 220, 131, 23))
        self.MoveToStartPoint.setObjectName(_fromUtf8("MoveToStartPoint"))
        self.graphicsView_VL = QtGui.QGraphicsView(Dialog)
        self.graphicsView_VL.setGeometry(QtCore.QRect(300, 50, 301, 241))
        self.graphicsView_VL.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.graphicsView_VL.setMouseTracking(False)
        self.graphicsView_VL.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.graphicsView_VL.setViewportUpdateMode(QtGui.QGraphicsView.MinimalViewportUpdate)
        self.graphicsView_VL.setObjectName(_fromUtf8("graphicsView_VL"))
        self.graphicsView_XR = QtGui.QGraphicsView(Dialog)
        self.graphicsView_XR.setGeometry(QtCore.QRect(610, 50, 361, 241))
        self.graphicsView_XR.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.graphicsView_XR.setObjectName(_fromUtf8("graphicsView_XR"))
        self.tableView = QtGui.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(300, 330, 217, 200))
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableView.setObjectName(_fromUtf8("tableView"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        self.ModifyElement.setText(_translate("Dialog", "Modify Element", None))
        self.label_3.setText(_translate("Dialog", "Top-Left Corner", None))
        self.label_4.setText(_translate("Dialog", "Scan Area", None))
        self.label_5.setText(_translate("Dialog", "Sample Motor Position", None))
        self.label_6.setText(_translate("Dialog", "X:", None))
        self.label_7.setText(_translate("Dialog", "Y:", None))
        self.label_8.setText(_translate("Dialog", "Z:", None))
        self.label_9.setText(_translate("Dialog", "To:", None))
        self.label_10.setText(_translate("Dialog", "To:", None))
        self.label_11.setText(_translate("Dialog", "To:", None))
        self.label_12.setText(_translate("Dialog", "X:", None))
        self.label_13.setText(_translate("Dialog", "Y:", None))
        self.label_14.setText(_translate("Dialog", "H:", None))
        self.label_15.setText(_translate("Dialog", "W:", None))
        self.changeMotorPositionX.setText(_translate("Dialog", "Go", None))
        self.changeMotorPositionY.setText(_translate("Dialog", "Go", None))
        self.changeMotorPositionZ.setText(_translate("Dialog", "Go", None))
        self.minusMotorPositionX.setText(_translate("Dialog", "-", None))
        self.plusMotorPositionX.setText(_translate("Dialog", "+", None))
        self.plusMotorPositionY.setText(_translate("Dialog", "+", None))
        self.minusMotorPositionY.setText(_translate("Dialog", "-", None))
        self.plusMotorPositionZ.setText(_translate("Dialog", "+", None))
        self.minusMotorPositionZ.setText(_translate("Dialog", "-", None))
        self.label_17.setText(_translate("Dialog", "Scan Step Size", None))
        self.label_18.setText(_translate("Dialog", "X:", None))
        self.label_19.setText(_translate("Dialog", "Y:", None))
        self.label_20.setText(_translate("Dialog", "Dwell Time:", None))
        self.label_21.setText(_translate("Dialog", "ms/pt", None))
        self.label_22.setText(_translate("Dialog", "Time Left:", None))
        self.ExecuteScan.setText(_translate("Dialog", "Execute Scan", None))
        self.label_23.setText(_translate("Dialog", "        Visible Light View", None))
        self.label_24.setText(_translate("Dialog", "            X-ray View", None))
        self.MoveToStartPoint.setText(_translate("Dialog", "Move to Start Point", None))

