# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'specify_XANES_files.ui'
#
# Created: Fri Jul 11 11:25:48 2014
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(623, 889)
        self.sample_inputBox = QtGui.QGroupBox(Dialog)
        self.sample_inputBox.setGeometry(QtCore.QRect(10, 30, 481, 101))
        self.sample_inputBox.setObjectName(_fromUtf8("sample_inputBox"))
        self.samTxrm = QtGui.QRadioButton(self.sample_inputBox)
        self.samTxrm.setGeometry(QtCore.QRect(10, 30, 51, 17))
        self.samTxrm.setChecked(True)
        self.samTxrm.setObjectName(_fromUtf8("samTxrm"))
        self.samXrm = QtGui.QRadioButton(self.sample_inputBox)
        self.samXrm.setGeometry(QtCore.QRect(60, 30, 41, 17))
        self.samXrm.setObjectName(_fromUtf8("samXrm"))
        self.button_load_XANES = QtGui.QPushButton(self.sample_inputBox)
        self.button_load_XANES.setGeometry(QtCore.QRect(10, 60, 75, 23))
        self.button_load_XANES.setAutoDefault(False)
        self.button_load_XANES.setObjectName(_fromUtf8("button_load_XANES"))
        self.text_XANES_filename = QtGui.QLabel(self.sample_inputBox)
        self.text_XANES_filename.setGeometry(QtCore.QRect(110, 20, 361, 61))
        self.text_XANES_filename.setObjectName(_fromUtf8("text_XANES_filename"))
        self.bkg_inputBox = QtGui.QGroupBox(Dialog)
        self.bkg_inputBox.setGeometry(QtCore.QRect(10, 130, 481, 101))
        self.bkg_inputBox.setObjectName(_fromUtf8("bkg_inputBox"))
        self.bkgTxrm = QtGui.QRadioButton(self.bkg_inputBox)
        self.bkgTxrm.setGeometry(QtCore.QRect(10, 30, 51, 17))
        self.bkgTxrm.setChecked(True)
        self.bkgTxrm.setObjectName(_fromUtf8("bkgTxrm"))
        self.bkgXrm = QtGui.QRadioButton(self.bkg_inputBox)
        self.bkgXrm.setGeometry(QtCore.QRect(60, 30, 41, 17))
        self.bkgXrm.setObjectName(_fromUtf8("bkgXrm"))
        self.button_load_BKG = QtGui.QPushButton(self.bkg_inputBox)
        self.button_load_BKG.setGeometry(QtCore.QRect(10, 60, 75, 23))
        self.button_load_BKG.setAutoDefault(False)
        self.button_load_BKG.setObjectName(_fromUtf8("button_load_BKG"))
        self.text_BKG_filename = QtGui.QLabel(self.bkg_inputBox)
        self.text_BKG_filename.setGeometry(QtCore.QRect(110, 20, 361, 71))
        self.text_BKG_filename.setObjectName(_fromUtf8("text_BKG_filename"))
        self.alignment_checkBox = QtGui.QCheckBox(Dialog)
        self.alignment_checkBox.setGeometry(QtCore.QRect(20, 240, 151, 17))
        self.alignment_checkBox.setObjectName(_fromUtf8("alignment_checkBox"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 0, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.reference_inputBox = QtGui.QGroupBox(Dialog)
        self.reference_inputBox.setGeometry(QtCore.QRect(10, 270, 481, 141))
        self.reference_inputBox.setObjectName(_fromUtf8("reference_inputBox"))
        self.label_2 = QtGui.QLabel(self.reference_inputBox)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 51, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.reference_inputBox)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.reference_inputBox)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 101, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.load_ref1 = QtGui.QPushButton(self.reference_inputBox)
        self.load_ref1.setGeometry(QtCore.QRect(120, 20, 101, 23))
        self.load_ref1.setAutoDefault(False)
        self.load_ref1.setObjectName(_fromUtf8("load_ref1"))
        self.load_ref2 = QtGui.QPushButton(self.reference_inputBox)
        self.load_ref2.setGeometry(QtCore.QRect(120, 60, 101, 23))
        self.load_ref2.setAutoDefault(False)
        self.load_ref2.setObjectName(_fromUtf8("load_ref2"))
        self.load_ref3 = QtGui.QPushButton(self.reference_inputBox)
        self.load_ref3.setGeometry(QtCore.QRect(120, 100, 101, 23))
        self.load_ref3.setAutoDefault(False)
        self.load_ref3.setObjectName(_fromUtf8("load_ref3"))
        self.ref1name = QtGui.QLabel(self.reference_inputBox)
        self.ref1name.setGeometry(QtCore.QRect(230, 20, 241, 21))
        self.ref1name.setObjectName(_fromUtf8("ref1name"))
        self.ref2name = QtGui.QLabel(self.reference_inputBox)
        self.ref2name.setGeometry(QtCore.QRect(230, 60, 241, 21))
        self.ref2name.setObjectName(_fromUtf8("ref2name"))
        self.ref3name = QtGui.QLabel(self.reference_inputBox)
        self.ref3name.setGeometry(QtCore.QRect(230, 100, 241, 21))
        self.ref3name.setObjectName(_fromUtf8("ref3name"))
        self.back_normal = QtGui.QPushButton(Dialog)
        self.back_normal.setGeometry(QtCore.QRect(20, 420, 121, 31))
        self.back_normal.setAutoDefault(False)
        self.back_normal.setObjectName(_fromUtf8("back_normal"))
        self.status_bkgnorm = QtGui.QLabel(Dialog)
        self.status_bkgnorm.setGeometry(QtCore.QRect(150, 430, 71, 16))
        self.status_bkgnorm.setObjectName(_fromUtf8("status_bkgnorm"))
        self.orgView = QtGui.QGraphicsView(Dialog)
        self.orgView.setGeometry(QtCore.QRect(20, 460, 381, 381))
        self.orgView.setObjectName(_fromUtf8("orgView"))
        self.scaleBox = QtGui.QGroupBox(Dialog)
        self.scaleBox.setGeometry(QtCore.QRect(410, 460, 81, 381))
        self.scaleBox.setObjectName(_fromUtf8("scaleBox"))
        self.text_maxscale = QtGui.QLabel(self.scaleBox)
        self.text_maxscale.setGeometry(QtCore.QRect(10, 10, 61, 20))
        self.text_maxscale.setObjectName(_fromUtf8("text_maxscale"))
        self.label_7 = QtGui.QLabel(self.scaleBox)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 41, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.slider_img_maxscale = QtGui.QScrollBar(self.scaleBox)
        self.slider_img_maxscale.setGeometry(QtCore.QRect(30, 50, 21, 121))
        self.slider_img_maxscale.setOrientation(QtCore.Qt.Vertical)
        self.slider_img_maxscale.setObjectName(_fromUtf8("slider_img_maxscale"))
        self.label_8 = QtGui.QLabel(self.scaleBox)
        self.label_8.setGeometry(QtCore.QRect(30, 170, 21, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.text_minscale = QtGui.QLabel(self.scaleBox)
        self.text_minscale.setGeometry(QtCore.QRect(10, 190, 61, 20))
        self.text_minscale.setObjectName(_fromUtf8("text_minscale"))
        self.slider_img_minscale = QtGui.QScrollBar(self.scaleBox)
        self.slider_img_minscale.setGeometry(QtCore.QRect(30, 230, 21, 121))
        self.slider_img_minscale.setOrientation(QtCore.Qt.Vertical)
        self.slider_img_minscale.setObjectName(_fromUtf8("slider_img_minscale"))
        self.label_10 = QtGui.QLabel(self.scaleBox)
        self.label_10.setGeometry(QtCore.QRect(30, 210, 31, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.scaleBox)
        self.label_11.setGeometry(QtCore.QRect(30, 360, 21, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.slider_img = QtGui.QScrollBar(Dialog)
        self.slider_img.setGeometry(QtCore.QRect(20, 840, 381, 21))
        self.slider_img.setOrientation(QtCore.Qt.Horizontal)
        self.slider_img.setObjectName(_fromUtf8("slider_img"))
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(80, 860, 81, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.current_img = QtGui.QLineEdit(Dialog)
        self.current_img.setGeometry(QtCore.QRect(170, 860, 51, 20))
        self.current_img.setObjectName(_fromUtf8("current_img"))
        self.total_img = QtGui.QLabel(Dialog)
        self.total_img.setGeometry(QtCore.QRect(230, 860, 111, 21))
        self.total_img.setObjectName(_fromUtf8("total_img"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.sample_inputBox.setTitle(_translate("Dialog", "Sample File", None))
        self.samTxrm.setText(_translate("Dialog", "txrm", None))
        self.samXrm.setText(_translate("Dialog", "xrm", None))
        self.button_load_XANES.setText(_translate("Dialog", "Browse Data", None))
        self.text_XANES_filename.setText(_translate("Dialog", "                                 XANES Sample directory & filename", None))
        self.bkg_inputBox.setTitle(_translate("Dialog", "Background File", None))
        self.bkgTxrm.setText(_translate("Dialog", "txrm", None))
        self.bkgXrm.setText(_translate("Dialog", "xrm", None))
        self.button_load_BKG.setText(_translate("Dialog", "Background", None))
        self.text_BKG_filename.setText(_translate("Dialog", "                              XANES Background directory & filename", None))
        self.alignment_checkBox.setText(_translate("Dialog", "apply pre-alignment in txrm", None))
        self.label.setText(_translate("Dialog", "Input Data", None))
        self.reference_inputBox.setTitle(_translate("Dialog", "Load Reference", None))
        self.label_2.setText(_translate("Dialog", "Ref1 - Red", None))
        self.label_3.setText(_translate("Dialog", "Ref2 - Green", None))
        self.label_4.setText(_translate("Dialog", "Ref3 - Blue(optional)", None))
        self.load_ref1.setText(_translate("Dialog", "Load Reference 1", None))
        self.load_ref2.setText(_translate("Dialog", "Load Reference 2", None))
        self.load_ref3.setText(_translate("Dialog", "Load Reference 3", None))
        self.ref1name.setText(_translate("Dialog", "                      no reference loaded", None))
        self.ref2name.setText(_translate("Dialog", "                      no reference loaded", None))
        self.ref3name.setText(_translate("Dialog", "                      no reference loaded", None))
        self.back_normal.setText(_translate("Dialog", "Load and Show Image", None))
        self.status_bkgnorm.setText(_translate("Dialog", "Status: none", None))
        self.scaleBox.setTitle(_translate("Dialog", "Scale", None))
        self.text_maxscale.setText(_translate("Dialog", "Max         %", None))
        self.label_7.setText(_translate("Dialog", "  100%", None))
        self.label_8.setText(_translate("Dialog", "0%", None))
        self.text_minscale.setText(_translate("Dialog", "Min          %", None))
        self.label_10.setText(_translate("Dialog", "100%", None))
        self.label_11.setText(_translate("Dialog", "0%", None))
        self.label_12.setText(_translate("Dialog", "Image Number:", None))
        self.total_img.setText(_translate("Dialog", "/ Total Image Number", None))

